### ISSUE TITLE
User reports failing to cast to Chromecast

### ISSUE THREAD

**Issue by daneren2005** [daneren2005/Subsonic#1030]
From Googling it looks like the only real fix would be to upgrade to a modern version of the cast support library.  IIRC upgrading is a major undertaking though, so not sure whether I really care enough to do that.  Relevant issue: https://issuetracker.google.com/issues/72880677.

java.lang.IllegalStateException: Not connected to a device
	at com.google.android.gms.cast.internal.zze.zzmY(Unknown Source:20)
	at com.google.android.gms.cast.internal.zze.getApplicationStatus(Unknown Source:0)
	at com.google.android.gms.cast.Cast$CastApi$zza.getApplicationStatus(Unknown Source:8)
	at github.daneren2005.dsub.service.ChromeCastController$1.onApplicationStatusChanged(ChromeCastController.java:87)
	at com.google.android.gms.cast.internal.zze.zza(Unknown Source:5000)
	at com.google.android.gms.cast.internal.zze$zzb$3.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:8125)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:496)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1100)

**Comment by madfusker** [comment]
I can still cast to CC audios when using the demo server that doesn't use SSL, but on my subsonic docker container inside my network it just stalls out because of SSL, even when selecting the localhost proxy in the app settings.  The CC are all in the same network 192.168.1.blah.

I would LOVE to find a fix for this as ALL my playlists are in Subsonic and I love this app!  I can't live without it really.  The home integration ability through this app and CC is simply amazing when simple casting works.  Hopefully you can find a way to make it work.  Thanks.

**Comment by vbc4ejyg** [comment]
I have just figured out that using a combination of the provided local proxy feature in the app's "Casting" section, **PLUS** enabling pfSense's NAT reflection (NAT + Proxy) in my port forward settings, it's now allowing me to cast to all my chromecast audios.  This means on my internal network with my phone on a 192.168.1.190 IP for example, can now cast to a Chromecast audio (or group of them) on an IP such as 192.168.1.100 internally.  I now can use DSub again for whole house audio!  Whoot whoot!

Totally understand the extra work involved for the modern casting library....but it also feels like casting will be around for quite a while, and DSub is the best app in the market by a long ways!  Keep up the good work.
