### ISSUE TITLE
errors resource not found or wrong username/password

### ISSUE THREAD

**Issue by GunbleR** [daneren2005/Subsonic#1033]
hello.
got 2 devices: samsung s10+, android 10
Chinese android head unit, android 9.
samsung works fine, HU on version 5.5.0+ fails to run dsub.
on server connection test and on library refresh everything works fine.
but only after i enter artist folder in library, on test server & my server i get ether "resource not found, please check the server address" or "wrong username or password".
moving back to 5.4.4 fixes the issue on h.u.

subsonic log:
`[2020-11-17 21:32:23,424] INFO LoginFailureLogger - Login failed for [***] from [10.0.3.81]`

reverse-proxy access log, i dont know why i got two tokens, same thing happened the first time i got that problem:
```
[ip] - GunbleR [17/Nov/2020:21:44:15 +0200] "GET /rest/getUser.view?u=GunbleR&p=enc:null&v=1.2.0&c=DSub&username=GunbleR HTTP/1.1" 401 1414 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:44:15 +0200] "GET /rest/getRandomSongs.view?u=GunbleR&p=enc:null&v=1.2.0&c=DSub&size=50 HTTP/1.1" 401 1421 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:44:15 +0200] "GET /rest/getMusicFolders.view?u=GunbleR&p=enc:null&v=1.2.0&c=DSub HTTP/1.1" 401 1422 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:44:15 +0200] "GET /rest/getUser.view?u=GunbleR&p=enc:null&v=1.2.0&c=DSub&username=GunbleR HTTP/1.1" 401 1414 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:44:16 +0200] "GET /rest/getMusicFolders.view?u=GunbleR&p=enc:null&v=1.2.0&c=DSub HTTP/1.1" 401 1422 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:44:18 +0200] "GET /rest/getMusicFolders.view?u=GunbleR&p=enc:null&v=1.2.0&c=DSub HTTP/1.1" 401 1422 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:44:26 +0200] "GET /rest/getRandomSongs.view?u=GunbleR&p=enc:null&v=1.2.0&c=DSub&size=50 HTTP/1.1" 401 1421 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:46:04 +0200] "GET /rest/getUser.view?u=GunbleR&p=enc:null&v=1.2.0&c=DSub&username=GunbleR HTTP/1.1" 401 1414 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:46:04 +0200] "GET /rest/getMusicFolders.view?u=GunbleR&p=enc:null&v=1.2.0&c=DSub HTTP/1.1" 401 1422 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:46:06 +0200] "GET /rest/getRandomSongs.view?u=GunbleR&p=enc:null&v=1.2.0&c=DSub&size=50 HTTP/1.1" 401 1421 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:46:06 +0200] "GET /rest/getUser.view?u=GunbleR&p=enc:null&v=1.2.0&c=DSub&username=GunbleR HTTP/1.1" 401 1414 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:46:13 +0200] "GET /rest/getMusicFolders.view?u=GunbleR&p=enc:null&v=1.2.0&c=DSub HTTP/1.1" 401 1422 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:46:16 +0200] "GET /rest/getRandomSongs.view?u=GunbleR&p=enc:null&v=1.2.0&c=DSub&size=50 HTTP/1.1" 401 1421 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:46:17 +0200] "GET /rest/getMusicFolders.view?u=GunbleR&p=enc:null&v=1.2.0&c=DSub HTTP/1.1" 401 1422 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:46:18 +0200] "GET /rest/getMusicFolders.view?u=GunbleR&p=enc:null&v=1.2.0&c=DSub HTTP/1.1" 401 1422 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:46:51 +0200] "GET /rest/ping.view?u=GunbleR&p=enc:[somenumber]&v=1.2.0&c=DSub HTTP/1.1" 200 140 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:46:52 +0200] "GET /rest/getLicense.view?u=GunbleR&s=[slt01]&t=[tkn01]&v=1.2.0&c=DSub HTTP/1.1" 200 240 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:46:55 +0200] "GET /rest/getUser.view?u=GunbleR&s=[slt01]&t=[tkn01]&v=1.2.0&c=DSub&username=GunbleR HTTP/1.1" 200 340 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:46:56 +0200] "GET /rest/getMusicFolders.view?u=GunbleR&s=[slt01]&t=[tkn01]&v=1.2.0&c=DSub HTTP/1.1" 200 194 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:46:57 +0200] "GET /rest/getMusicFolders.view?u=GunbleR&s=[slt01]&t=[tkn01]&v=1.2.0&c=DSub HTTP/1.1" 200 194 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:46:57 +0200] "GET /rest/getIndexes.view?u=GunbleR&s=[slt01]&t=[tkn01]&v=1.2.0&c=DSub HTTP/1.1" 200 3340 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:46:59 +0200] "GET /rest/getMusicDirectory.view?u=GunbleR&s=[slt01]&t=[tkn01]&v=1.2.0&c=DSub&id=9 HTTP/1.1" 200 625 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:46:59 +0200] "GET /rest/getCoverArt.view?u=GunbleR&s=[slt02]&t=[tkn02]&v=1.2.0&c=DSub&id=21344 HTTP/1.1" 401 1418 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:46:59 +0200] "GET /rest/getArtistInfo.view?u=GunbleR&s=[slt02]&t=[tkn02]&v=1.2.0&c=DSub&id=9&includeNotPresent=true HTTP/1.1" 401 1420 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:46:59 +0200] "GET /rest/getCoverArt.view?u=GunbleR&s=[slt02]&t=[tkn02]&v=1.2.0&c=DSub&id=25661 HTTP/1.1" 401 1418 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:46:59 +0200] "GET /rest/getCoverArt.view?u=GunbleR&s=[slt02]&t=[tkn02]&v=1.2.0&c=DSub&id=25659 HTTP/1.1" 200 220 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:46:59 +0200] "GET /rest/getCoverArt.view?u=GunbleR&s=[slt02]&t=[tkn02]&v=1.2.0&c=DSub&id=1246 HTTP/1.1" 401 1418 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:47:06 +0200] "GET /rest/getMusicDirectory.view?u=GunbleR&s=[slt01]&t=[tkn01]&v=1.2.0&c=DSub&id=16433 HTTP/1.1" 200 539 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:47:07 +0200] "GET /rest/getCoverArt.view?u=GunbleR&s=[slt01]&t=[tkn01]&v=1.2.0&c=DSub&id=27293 HTTP/1.1" 401 1418 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:47:07 +0200] "GET /rest/getCoverArt.view?u=GunbleR&s=[slt02]&t=[tkn02]&v=1.2.0&c=DSub&id=27297 HTTP/1.1" 401 1418 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:47:07 +0200] "GET /rest/getArtistInfo.view?u=GunbleR&s=[slt02]&t=[tkn02]&v=1.2.0&c=DSub&id=16433&includeNotPresent=true HTTP/1.1" 401 1420 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:47:07 +0200] "GET /rest/getCoverArt.view?u=GunbleR&s=[slt02]&t=[tkn02]&v=1.2.0&c=DSub&id=27291 HTTP/1.1" 401 1418 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:47:11 +0200] "GET /rest/getMusicDirectory.view?u=GunbleR&s=[slt02]&t=[tkn02]&v=1.2.0&c=DSub&id=16433 HTTP/1.1" 401 1424 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:47:12 +0200] "GET /rest/getLicense.view?u=GunbleR&s=[slt01]&t=[tkn01]&v=1.2.0&c=DSub HTTP/1.1" 200 240 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:47:12 +0200] "GET /rest/getMusicDirectory.view?u=GunbleR&s=[slt02]&t=[tkn02]&v=1.2.0&c=DSub&id=9 HTTP/1.1" 200 220 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:47:12 +0200] "GET /rest/getArtistInfo.view?u=GunbleR&s=[slt02]&t=[tkn02]&v=1.2.0&c=DSub&id=9&includeNotPresent=true HTTP/1.1" 401 1420 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:47:13 +0200] "GET /rest/getCoverArt.view?u=GunbleR&s=[slt02]&t=[tkn02]&v=1.2.0&c=DSub&id=1247 HTTP/1.1" 401 1418 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:47:13 +0200] "GET /rest/getCoverArt.view?u=GunbleR&s=[slt02]&t=[tkn02]&v=1.2.0&c=DSub&id=1246 HTTP/1.1" 401 1418 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:47:13 +0200] "GET /rest/getCoverArt.view?u=GunbleR&s=[slt02]&t=[tkn02]&v=1.2.0&c=DSub&id=25661 HTTP/1.1" 401 1418 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:47:13 +0200] "GET /rest/getCoverArt.view?u=GunbleR&s=[slt02]&t=[tkn02]&v=1.2.0&c=DSub&id=25659 HTTP/1.1" 200 220 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:47:15 +0200] "GET /rest/getMusicDirectory.view?u=GunbleR&s=[slt01]&t=[tkn01]&v=1.2.0&c=DSub&id=16436 HTTP/1.1" 200 1306 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:47:16 +0200] "GET /rest/getCoverArt.view?u=GunbleR&s=[slt02]&t=[tkn02]&v=1.2.0&c=DSub&id=27378 HTTP/1.1" 401 1418 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:47:16 +0200] "GET /rest/getArtistInfo.view?u=GunbleR&s=[slt02]&t=[tkn02]&v=1.2.0&c=DSub&id=16436&includeNotPresent=true HTTP/1.1" 401 1420 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:47:16 +0200] "GET /rest/getCoverArt.view?u=GunbleR&s=[slt01]&t=[tkn01]&v=1.2.0&c=DSub&id=18903 HTTP/1.1" 401 1418 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:47:16 +0200] "GET /rest/getCoverArt.view?u=GunbleR&s=[slt02]&t=[tkn02]&v=1.2.0&c=DSub&id=18909 HTTP/1.1" 200 220 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:47:16 +0200] "GET /rest/getCoverArt.view?u=GunbleR&s=[slt02]&t=[tkn02]&v=1.2.0&c=DSub&id=27384 HTTP/1.1" 401 1418 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:47:19 +0200] "GET /rest/getMusicDirectory.view?u=GunbleR&s=[slt01]&t=[tkn01]&v=1.2.0&c=DSub&id=10092 HTTP/1.1" 200 293 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:47:19 +0200] "GET /rest/getArtistInfo.view?u=GunbleR&s=[slt01]&t=[tkn01]&v=1.2.0&c=DSub&id=10092&includeNotPresent=true HTTP/1.1" 401 1420 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:47:23 +0200] "GET /rest/getMusicDirectory.view?u=GunbleR&s=[slt01]&t=[tkn01]&v=1.2.0&c=DSub&id=58 HTTP/1.1" 200 298 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:47:24 +0200] "GET /rest/getArtistInfo.view?u=GunbleR&s=[slt01]&t=[tkn01]&v=1.2.0&c=DSub&id=58&includeNotPresent=true HTTP/1.1" 401 1420 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:47:42 +0200] "GET /rest/getMusicDirectory.view?u=GunbleR&s=[slt02]&t=[tkn02]&v=1.2.0&c=DSub&id=58 HTTP/1.1" 401 1424 "-" "DSub"
[ip] - GunbleR [17/Nov/2020:21:47:42 +0200] "GET /rest/getMusicDirectory.view?u=GunbleR&s=[slt02]&t=[tkn02]&v=1.2.0&c=DSub&id=8410 HTTP/1.1" 200 220 "-" "DSub"
```

edit:
token 2 is incorrect with salt 2, token 1 is correct
token 2 takes text null as password, adding more logs to 'code' above

**Comment by GunbleR** [comment]
also, i tried to:
install 5.4.4>try test server>update to 5.5.1>try test server>add my server.
results: test server still works on 5.5.1, my does not.

**Comment by daneren2005** [comment]
Are you able to grab the Android logs from the HU?  I don't think anything about the salting logic has even changed recently.  It sounds more like yet another device that screwed up one of the public API's, and the problem only manifests when targeting a more recent release of Android.

**Comment by GunbleR** [comment]
If By logs you mean catlog from root/adb, then unfortunately no.
 I dont think its about saulting, i think somewhere before it picks password as null and use it simultaneously with correct one

**Comment by daneren2005** [comment]
You should be able to grab logs from the Home menu - Send Logs as long as the device has the ability to send email

**Comment by daneren2005** [comment]
Seeing these errors from the error logs:
```
12-05 19:21:08.527 W/KeyStoreUtil( 2579): Password decryption failed
12-05 19:21:08.528 W/KeyStoreUtil( 2579): javax.crypto.AEADBadTagException
12-05 19:21:08.528 W/KeyStoreUtil( 2579): 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:517)
12-05 19:21:08.528 W/KeyStoreUtil( 2579): 	at javax.crypto.Cipher.doFinal(Cipher.java:2055)
12-05 19:21:08.528 W/KeyStoreUtil( 2579): 	at github.daneren2005.dsub.util.KeyStoreUtil.decrypt(KeyStoreUtil.java:134)
12-05 19:21:08.528 W/KeyStoreUtil( 2579): 	at github.daneren2005.dsub.service.RESTMusicService.getConnectionDirect(RESTMusicService.java:1919)
12-05 19:21:08.528 W/KeyStoreUtil( 2579): 	at github.daneren2005.dsub.service.RESTMusicService.getConnectionDirect(RESTMusicService.java:1873)
12-05 19:21:08.528 W/KeyStoreUtil( 2579): 	at github.daneren2005.dsub.service.RESTMusicService.getConnection(RESTMusicService.java:1821)
12-05 19:21:08.528 W/KeyStoreUtil( 2579): 	at github.daneren2005.dsub.service.RESTMusicService.getConnection(RESTMusicService.java:1815)
12-05 19:21:08.528 W/KeyStoreUtil( 2579): 	at github.daneren2005.dsub.service.RESTMusicService.getBitmapFromUrl(RESTMusicService.java:9812)
12-05 19:21:08.528 W/KeyStoreUtil( 2579): 	at github.daneren2005.dsub.service.RESTMusicService.getCoverArt(RESTMusicService.java:813)
12-05 19:21:08.528 W/KeyStoreUtil( 2579): 	at github.daneren2005.dsub.service.CachedMusicService.getCoverArt(CachedMusicService.java:746)
12-05 19:21:08.528 W/KeyStoreUtil( 2579): 	at github.daneren2005.dsub.util.ImageLoader$ImageTask.doInBackground(ImageLoader.java:453)
12-05 19:21:08.528 W/KeyStoreUtil( 2579): 	at github.daneren2005.dsub.util.ImageLoader$ImageTask.doInBackground(ImageLoader.java:432)
12-05 19:21:08.528 W/KeyStoreUtil( 2579): 	at github.daneren2005.dsub.util.BackgroundTask$Task.access$300(BackgroundTask.java:1208)
12-05 19:21:08.528 W/KeyStoreUtil( 2579): 	at github.daneren2005.dsub.util.BackgroundTask$TaskRunnable.run(BackgroundTask.java:319)
12-05 19:21:08.528 W/KeyStoreUtil( 2579): 	at java.lang.Thread.run(Thread.java:764)
12-05 19:21:08.528 W/KeyStoreUtil( 2579): Caused by: android.security.KeyStoreException: Signature/MAC verification failed
12-05 19:21:08.528 W/KeyStoreUtil( 2579): 	at android.security.KeyStore.getKeyStoreException(KeyStore.java:851)
12-05 19:21:08.528 W/KeyStoreUtil( 2579): 	at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:224)
12-05 19:21:08.528 W/KeyStoreUtil( 2579): 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
12-05 19:21:08.528 W/KeyStoreUtil( 2579): 	... 14 more
```

**Comment by daneren2005** [comment]
After doing a ton of searching, I see nothing obviously wrong with the code that is erroring out.  I think another night I am just going to spend some time making sure that we are able to decrypt our encrypted password before saving it as encrypted to fix devices which don't actually obey the spec like this.

**Comment by daneren2005** [comment]
Here is a test build which checks if the password it just encrypted is actually decryptable before saving it.  Can you try installing this and let me know if it fixes your issue?  You will need to go into the server settings, edit the password and click ok for the change to have an affect.  

[DSub 5.5.2-google-fix.apk.zip](https://github.com/daneren2005/Subsonic/files/5753051/DSub.5.5.2-google-fix.apk.zip)
