### ISSUE TITLE
Constant Crashes in Android 13

### ISSUE THREAD

**Issue by jeffgt14** [daneren2005/Subsonic#1129]
Pretty sure Android 13 changed something with audio because several audio related apps experienced random crashes constantly in Android 13 and most were fixed with recent updates. DSub will play about 30 seconds of music and just crash.

**Comment by basings** [comment]
I'm on android 13 and I don't experience random crashes.

**Comment by Forceu** [comment]
It happens to me quite often as well, most of the time when I open the home launcher or turn the display off, it crashes. Here is the most recent crashlog:

```
--------- beginning of crash
09-13 11:02:16.152 17364 17364 E AndroidRuntime: FATAL EXCEPTION: main
09-13 11:02:16.152 17364 17364 E AndroidRuntime: Process: github.daneren2005.dsub, PID: 17364
09-13 11:02:16.152 17364 17364 E AndroidRuntime: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 794784 bytes
09-13 11:02:16.152 17364 17364 E AndroidRuntime: Bundle stats:
09-13 11:02:16.152 17364 17364 E AndroidRuntime:   android:viewHierarchyState [size=4232]
09-13 11:02:16.152 17364 17364 E AndroidRuntime:     android:views [size=4184]
09-13 11:02:16.152 17364 17364 E AndroidRuntime:       0x7f090108 [size=1300]
09-13 11:02:16.152 17364 17364 E AndroidRuntime:   android:support:fragments [size=789580]
09-13 11:02:16.152 17364 17364 E AndroidRuntime: PersistableBundle stats:
09-13 11:02:16.152 17364 17364 E AndroidRuntime:   [null]
09-13 11:02:16.152 17364 17364 E AndroidRuntime: 	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:165)
09-13 11:02:16.152 17364 17364 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
09-13 11:02:16.152 17364 17364 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-13 11:02:16.152 17364 17364 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
09-13 11:02:16.152 17364 17364 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
09-13 11:02:16.152 17364 17364 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7918)
09-13 11:02:16.152 17364 17364 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-13 11:02:16.152 17364 17364 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-13 11:02:16.152 17364 17364 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
09-13 11:02:16.152 17364 17364 E AndroidRuntime: Caused by: android.os.TransactionTooLargeException: data parcel size 794784 bytes
09-13 11:02:16.152 17364 17364 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
09-13 11:02:16.152 17364 17364 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:584)
09-13 11:02:16.152 17364 17364 E AndroidRuntime: 	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1316)
09-13 11:02:16.152 17364 17364 E AndroidRuntime: 	at android.app.ActivityClient.activityStopped(ActivityClient.java:95)
09-13 11:02:16.152 17364 17364 E AndroidRuntime: 	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:154)
09-13 11:02:16.152 17364 17364 E AndroidRuntime: 	... 8 more
09-13 11:02:16.162  3070  5792 E MediaProvider: insertFileIfNecessary failed
09-13 11:02:16.162  3070  5792 E MediaProvider: java.lang.IllegalArgumentException: Primary directory null not allowed for content://media/external_primary/file; allowed directories are [Download, Documents]
09-13 11:02:16.162  3070  5792 E MediaProvider: 	at com.android.providers.media.MediaProvider.ensureFileColumns(MediaProvider.java:4036)
09-13 11:02:16.162  3070  5792 E MediaProvider: 	at com.android.providers.media.MediaProvider.ensureUniqueFileColumns(MediaProvider.java:3674)
09-13 11:02:16.162  3070  5792 E MediaProvider: 	at com.android.providers.media.MediaProvider.insertFile(MediaProvider.java:4458)
09-13 11:02:16.162  3070  5792 E MediaProvider: 	at com.android.providers.media.MediaProvider.insertInternal(MediaProvider.java:5047)
09-13 11:02:16.162  3070  5792 E MediaProvider: 	at com.android.providers.media.MediaProvider.insert(MediaProvider.java:4746)
09-13 11:02:16.162  3070  5792 E MediaProvider: 	at com.android.providers.media.MediaProvider.insertFileForFuse(MediaProvider.java:9405)
09-13 11:02:16.162  3070  5792 E MediaProvider: 	at com.android.providers.media.MediaProvider.insertFileIfNecessaryForFuse(MediaProvider.java:9500)
09-13 11:02:16.164 17364 17364 E SubsonicActivity: Failed to write stack trace to /storage/emulated/0/dsub-stacktrace.txt
09-13 11:02:16.164 17364 17364 E SubsonicActivity: java.io.FileNotFoundException: /storage/emulated/0/dsub-stacktrace.txt: open failed: EPERM (Operation not permitted)
09-13 11:02:16.164 17364 17364 E SubsonicActivity: 	at libcore.io.IoBridge.open(IoBridge.java:574)
09-13 11:02:16.164 17364 17364 E SubsonicActivity: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
09-13 11:02:16.164 17364 17364 E SubsonicActivity: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
09-13 11:02:16.164 17364 17364 E SubsonicActivity: 	at java.io.PrintWriter.<init>(PrintWriter.java:309)
09-13 11:02:16.164 17364 17364 E SubsonicActivity: 	at github.daneren2005.dsub.activity.SubsonicActivity$SubsonicUncaughtExceptionHandler.uncaughtException(SubsonicActivity.java:1275)
09-13 11:02:16.164 17364 17364 E SubsonicActivity: 	at org.chromium.base.JavaExceptionReporter.uncaughtException(chromium-TrichromeWebViewGoogle6432.aab-stable-584517233:17)
09-13 11:02:16.164 17364 17364 E SubsonicActivity: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
09-13 11:02:16.164 17364 17364 E SubsonicActivity: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
09-13 11:02:16.164 17364 17364 E SubsonicActivity: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
09-13 11:02:16.164 17364 17364 E SubsonicActivity: Caused by: android.system.ErrnoException: open failed: EPERM (Operation not permitted)
09-13 11:02:16.164 17364 17364 E SubsonicActivity: 	at libcore.io.Linux.open(Native Method)
09-13 11:02:16.164 17364 17364 E SubsonicActivity: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
09-13 11:02:16.164 17364 17364 E SubsonicActivity: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
09-13 11:02:16.164 17364 17364 E SubsonicActivity: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
09-13 11:02:16.164 17364 17364 E SubsonicActivity: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7804)
09-13 11:02:16.164 17364 17364 E SubsonicActivity: 	at libcore.io.IoBridge.open(IoBridge.java:560)
09-13 11:02:16.164 17364 17364 E SubsonicActivity: 	... 8 more
09-13 11:02:16.310   437   437 E BpTransactionCompletedListener: Failed to transact (-32)
09-13 11:02:34.390  1351  1664 E ContextHubClientManager: Cannot send message to unregistered client (host endpoint ID = -28638)
09-13 11:02:34.390  1351  1664 E ContextHubClientManager: Cannot send message to unregistered client (host endpoint ID = -28638)
09-13 11:02:39.043  1351  1664 E ContextHubClientManager: Cannot send message to unregistered client (host endpoint ID = -28640)
09-13 11:02:47.387 20394 20394 E .android.as.oss: Not starting debugger since process cannot load the jdwp agent.

```

and
```

09-13 11:07:40.929 20810 20810 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 794744)
09-13 11:07:40.954 20810 20810 E AndroidRuntime: FATAL EXCEPTION: main
09-13 11:07:40.954 20810 20810 E AndroidRuntime: Process: github.daneren2005.dsub, PID: 20810
09-13 11:07:40.954 20810 20810 E AndroidRuntime: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 794744 bytes
09-13 11:07:40.954 20810 20810 E AndroidRuntime: Bundle stats:
09-13 11:07:40.954 20810 20810 E AndroidRuntime:   android:viewHierarchyState [size=4208]
09-13 11:07:40.954 20810 20810 E AndroidRuntime:     android:views [size=4104]
09-13 11:07:40.954 20810 20810 E AndroidRuntime:       0x7f090108 [size=1300]
09-13 11:07:40.954 20810 20810 E AndroidRuntime:   android:support:fragments [size=789564]
09-13 11:07:40.954 20810 20810 E AndroidRuntime: PersistableBundle stats:
09-13 11:07:40.954 20810 20810 E AndroidRuntime:   [null]
09-13 11:07:40.954 20810 20810 E AndroidRuntime: 	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:165)
09-13 11:07:40.954 20810 20810 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:942)
09-13 11:07:40.954 20810 20810 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
09-13 11:07:40.954 20810 20810 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
09-13 11:07:40.954 20810 20810 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
09-13 11:07:40.954 20810 20810 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7918)
09-13 11:07:40.954 20810 20810 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-13 11:07:40.954 20810 20810 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
09-13 11:07:40.954 20810 20810 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
09-13 11:07:40.954 20810 20810 E AndroidRuntime: Caused by: android.os.TransactionTooLargeException: data parcel size 794744 bytes
09-13 11:07:40.954 20810 20810 E AndroidRuntime: 	at android.os.BinderProxy.transactNative(Native Method)
09-13 11:07:40.954 20810 20810 E AndroidRuntime: 	at android.os.BinderProxy.transact(BinderProxy.java:584)
09-13 11:07:40.954 20810 20810 E AndroidRuntime: 	at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1316)
09-13 11:07:40.954 20810 20810 E AndroidRuntime: 	at android.app.ActivityClient.activityStopped(ActivityClient.java:95)
09-13 11:07:40.954 20810 20810 E AndroidRuntime: 	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:154)
09-13 11:07:40.954 20810 20810 E AndroidRuntime: 	... 8 more
09-13 11:07:40.962  3070  3285 E MediaProvider: insertFileIfNecessary failed
09-13 11:07:40.962  3070  3285 E MediaProvider: java.lang.IllegalArgumentException: Primary directory null not allowed for content://media/external_primary/file; allowed directories are [Download, Documents]
09-13 11:07:40.962  3070  3285 E MediaProvider: 	at com.android.providers.media.MediaProvider.ensureFileColumns(MediaProvider.java:4036)
09-13 11:07:40.962  3070  3285 E MediaProvider: 	at com.android.providers.media.MediaProvider.ensureUniqueFileColumns(MediaProvider.java:3674)
09-13 11:07:40.962  3070  3285 E MediaProvider: 	at com.android.providers.media.MediaProvider.insertFile(MediaProvider.java:4458)
09-13 11:07:40.962  3070  3285 E MediaProvider: 	at com.android.providers.media.MediaProvider.insertInternal(MediaProvider.java:5047)
09-13 11:07:40.962  3070  3285 E MediaProvider: 	at com.android.providers.media.MediaProvider.insert(MediaProvider.java:4746)
09-13 11:07:40.962  3070  3285 E MediaProvider: 	at com.android.providers.media.MediaProvider.insertFileForFuse(MediaProvider.java:9405)
09-13 11:07:40.962  3070  3285 E MediaProvider: 	at com.android.providers.media.MediaProvider.insertFileIfNecessaryForFuse(MediaProvider.java:9500)
09-13 11:07:40.963 20810 20810 E SubsonicActivity: Failed to write stack trace to /storage/emulated/0/dsub-stacktrace.txt
09-13 11:07:40.963 20810 20810 E SubsonicActivity: java.io.FileNotFoundException: /storage/emulated/0/dsub-stacktrace.txt: open failed: EPERM (Operation not permitted)
09-13 11:07:40.963 20810 20810 E SubsonicActivity: 	at libcore.io.IoBridge.open(IoBridge.java:574)
09-13 11:07:40.963 20810 20810 E SubsonicActivity: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
09-13 11:07:40.963 20810 20810 E SubsonicActivity: 	at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
09-13 11:07:40.963 20810 20810 E SubsonicActivity: 	at java.io.PrintWriter.<init>(PrintWriter.java:309)
09-13 11:07:40.963 20810 20810 E SubsonicActivity: 	at github.daneren2005.dsub.activity.SubsonicActivity$SubsonicUncaughtExceptionHandler.uncaughtException(SubsonicActivity.java:1275)
09-13 11:07:40.963 20810 20810 E SubsonicActivity: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
09-13 11:0
```7:40.963 20810 20810 E SubsonicActivity: 	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
09-13 11:07:40.963 20810 20810 E SubsonicActivity: 	at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
09-13 11:07:40.963 20810 20810 E SubsonicActivity: Caused by: android.system.ErrnoException: open failed: EPERM (Operation not permitted)
09-13 11:07:40.963 20810 20810 E SubsonicActivity: 	at libcore.io.Linux.open(Native Method)
09-13 11:07:40.963 20810 20810 E SubsonicActivity: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
09-13 11:07:40.963 20810 20810 E SubsonicActivity: 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
09-13 11:07:40.963 20810 20810 E SubsonicActivity: 	at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
09-13 11:07:40.963 20810 20810 E SubsonicActivity: 	at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7804)
09-13 11:07:40.963 20810 20810 E SubsonicActivity: 	at libcore.io.IoBridge.open(IoBridge.java:560)
09-13 11:07:40.963 20810 20810 E SubsonicActivity: 	... 7 more

**Comment by ivan-avalos** [comment]
My theory is that the `TransactionTooLargeException` error happens because playing in the background is achieved using an Android service. When the app switches to background playback, it tries to send the playback state to the service via an IPC operation, which has a data transfer limit. When a large enough playlist is in the queue, the data size of the playback state exceeds this limit, so the switch to background crashes the app.
