### ISSUE TITLE
App crashes when put to background after playing playlist

### ISSUE THREAD

**Issue by D3viantS4ge** [daneren2005/Subsonic#1165]
DSub crashes after playing the playlist and subsequently minimizing the app to background. After restarting the app, pressing the play button and then minimizing the app plays the playlist without crashing. This only happens with one specific playlist.

### logcat:
```
06-08 11:59:23.334 17552 17552 W BpBinder: Large outgoing transaction of 599216 bytes, interface descriptor , code 6
06-08 11:59:23.334 17552 17552 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 599216)
06-08 11:59:23.334  1655  3099 W ActivityManager: pid 17552 github.daneren2005.dsub sent binder code 6 with flags 1 to frozen apps and got error -2147483646
06-08 11:59:23.344 17552 17552 E AndroidRuntime: FATAL EXCEPTION: main
06-08 11:59:23.344 17552 17552 E AndroidRuntime: Process: github.daneren2005.dsub, PID: 17552
06-08 11:59:23.344 17552 17552 E AndroidRuntime: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 599216 bytes
06-08 11:59:23.344 17552 17552 E AndroidRuntime: Bundle stats:
06-08 11:59:23.344 17552 17552 E AndroidRuntime:   android:viewHierarchyState [size=4780]
06-08 11:59:23.344 17552 17552 E AndroidRuntime:     android:views [size=4676]
06-08 11:59:23.344 17552 17552 E AndroidRuntime:       0x7f090108 [size=1496]
06-08 11:59:23.344 17552 17552 E AndroidRuntime:   android:support:fragments [size=593464]
06-08 11:59:23.344 17552 17552 E AndroidRuntime: PersistableBundle stats:
06-08 11:59:23.344 17552 17552 E AndroidRuntime:   [null]
06-08 11:59:23.344 17552 17552 E AndroidRuntime:        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:146)
06-08 11:59:23.344 17552 17552 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:959)
06-08 11:59:23.344 17552 17552 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
06-08 11:59:23.344 17552 17552 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:232)
06-08 11:59:23.344 17552 17552 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:317)
06-08 11:59:23.344 17552 17552 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:8501)
06-08 11:59:23.344 17552 17552 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-08 11:59:23.344 17552 17552 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
06-08 11:59:23.344 17552 17552 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
06-08 11:59:23.344 17552 17552 E AndroidRuntime: Caused by: android.os.TransactionTooLargeException: data parcel size 599216 bytes
06-08 11:59:23.344 17552 17552 E AndroidRuntime:        at android.os.BinderProxy.transactNative(Native Method)
06-08 11:59:23.344 17552 17552 E AndroidRuntime:        at android.os.BinderProxy.transact(BinderProxy.java:586)
06-08 11:59:23.344 17552 17552 E AndroidRuntime:        at android.app.IActivityClientController$Stub$Proxy.activityStopped(IActivityClientController.java:1459)
06-08 11:59:23.344 17552 17552 E AndroidRuntime:        at android.app.ActivityClient.activityStopped(ActivityClient.java:98)
06-08 11:59:23.344 17552 17552 E AndroidRuntime:        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:135)
06-08 11:59:23.344 17552 17552 E AndroidRuntime:        ... 8 more
06-08 11:59:23.407  4855  5226 E MediaProvider: insertFileIfNecessary failed
06-08 11:59:23.407  4855  5226 E MediaProvider: java.lang.IllegalArgumentException: Primary directory null not allowed for content://media/external_primary/file; allowed directories are [Download, Documents]
06-08 11:59:23.407  4855  5226 E MediaProvider:         at com.android.providers.media.MediaProvider.ensureFileColumns(MediaProvider.java:4565)
06-08 11:59:23.407  4855  5226 E MediaProvider:         at com.android.providers.media.MediaProvider.ensureUniqueFileColumns(MediaProvider.java:4189)
06-08 11:59:23.407  4855  5226 E MediaProvider:         at com.android.providers.media.MediaProvider.insertFile(MediaProvider.java:4987)
06-08 11:59:23.407  4855  5226 E MediaProvider:         at com.android.providers.media.MediaProvider.insertInternal(MediaProvider.java:5582)
06-08 11:59:23.407  4855  5226 E MediaProvider:         at com.android.providers.media.MediaProvider.insert(MediaProvider.java:5275)
06-08 11:59:23.407  4855  5226 E MediaProvider:         at com.android.providers.media.MediaProvider.insertFileForFuse(MediaProvider.java:10182)
06-08 11:59:23.407  4855  5226 E MediaProvider:         at com.android.providers.media.MediaProvider.insertFileIfNecessaryForFuse(MediaProvider.java:10277)
06-08 11:59:23.407 17552 17552 E SubsonicActivity: Failed to write stack trace to /storage/emulated/0/dsub-stacktrace.txt
06-08 11:59:23.407 17552 17552 E SubsonicActivity: java.io.FileNotFoundException: /storage/emulated/0/dsub-stacktrace.txt: open failed: EPERM (Operation not permitted)
06-08 11:59:23.407 17552 17552 E SubsonicActivity:      at libcore.io.IoBridge.open(IoBridge.java:574)
06-08 11:59:23.407 17552 17552 E SubsonicActivity:      at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
06-08 11:59:23.407 17552 17552 E SubsonicActivity:      at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
06-08 11:59:23.407 17552 17552 E SubsonicActivity:      at java.io.PrintWriter.<init>(PrintWriter.java:309)
06-08 11:59:23.407 17552 17552 E SubsonicActivity:      at github.daneren2005.dsub.activity.SubsonicActivity$SubsonicUncaughtExceptionHandler.uncaughtException(SubsonicActivity.java:1275)
06-08 11:59:23.407 17552 17552 E SubsonicActivity:      at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1071)
06-08 11:59:23.407 17552 17552 E SubsonicActivity:      at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1066)
06-08 11:59:23.407 17552 17552 E SubsonicActivity:      at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
06-08 11:59:23.407 17552 17552 E SubsonicActivity: Caused by: android.system.ErrnoException: open failed: EPERM (Operation not permitted)
06-08 11:59:23.407 17552 17552 E SubsonicActivity:      at libcore.io.Linux.open(Native Method)
06-08 11:59:23.407 17552 17552 E SubsonicActivity:      at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
06-08 11:59:23.407 17552 17552 E SubsonicActivity:      at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
06-08 11:59:23.407 17552 17552 E SubsonicActivity:      at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
06-08 11:59:23.407 17552 17552 E SubsonicActivity:      at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8387)
06-08 11:59:23.407 17552 17552 E SubsonicActivity:      at libcore.io.IoBridge.open(IoBridge.java:560)
06-08 11:59:23.407 17552 17552 E SubsonicActivity:      ... 7 more
06-08 11:59:23.414  1655  3099 W ActivityTaskManager:   Force finishing activity github.daneren2005.dsub/.activity.SubsonicFragmentActivity
```

**Comment by curiousercreative** [comment]
More accurately, navigating to anything via "library" while online (rather than offline mode) and backgrounding will cause a crash

**Comment by curiousercreative** [comment]
For anyone stumbling in here, this has been fixed on a fork: https://github.com/paroj/DSub2000/pull/86
