### ISSUE TITLE
Refresh on Empty Podcast Channel - Crash

### ISSUE THREAD

**Issue by daneren2005** [daneren2005/Subsonic#459]
DSub crashes when refreshing on a empty podcast channel (I assume when there is something there after refresh)

**Comment by daneren2005** [comment]
ava.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
at java.util.ArrayList.get(ArrayList.java:310)
at github.daneren2005.dsub.view.HeaderGridView$HeaderViewGridAdapter.getView(HeaderGridView.java:627)
at github.daneren2005.dsub.view.HeaderGridView.getRowHeight(HeaderGridView.java:315)
at github.daneren2005.dsub.view.HeaderGridView.setAdapter(HeaderGridView.java:359)
at github.daneren2005.dsub.fragments.SelectDirectoryFragment.finishLoading(SelectDirectoryFragment.java:772)
at github.daneren2005.dsub.fragments.SelectDirectoryFragment.access$500(SelectDirectoryFragment.java:77)
at github.daneren2005.dsub.fragments.SelectDirectoryFragment$LoadTask.done(SelectDirectoryFragment.java:713)
at github.daneren2005.dsub.fragments.SelectDirectoryFragment$LoadTask.done(SelectDirectoryFragment.java:669)
at github.daneren2005.dsub.util.TabBackgroundTask$1.onDone(TabBackgroundTask.java:26)
at github.daneren2005.dsub.util.BackgroundTask$Task$1.run(BackgroundTask.java:204)
