### ISSUE TITLE
Corrupted album art crashes the app

### ISSUE THREAD

**Issue by bazsy01** [daneren2005/Subsonic#739]
Playing anything from the album with a corrupted jpg as album art resulted in a system reboot. Restarting the app always crashed with this exception:
```
10-01 11:06:04.645 9068-9068/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: github.daneren2005.dsub, PID: 9068
                                                 java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Bitmap$Config.nativeInt' on a null object reference
                                                     at android.graphics.Bitmap.copy(Bitmap.java:560)
                                                     at android.widget.RemoteViews$BitmapCache.clone(RemoteViews.java:1015)
                                                     at android.widget.RemoteViews.clone(RemoteViews.java:1928)
                                                     at android.app.Notification.cloneInto(Notification.java:1518)
                                                     at android.app.Notification.clone(Notification.java:1492)
                                                     at android.app.NotificationManager.notify(NotificationManager.java:227)
                                                     at android.app.NotificationManager.notify(NotificationManager.java:194)
                                                     at github.daneren2005.dsub.util.Notifications$2.run(Notifications.java:116)
                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:234)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5526)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by daneren2005** [comment]
That will just stop the app from crashing.  There isn't really anything I can do about the Notification manager on your device being so fragile that it refuses to create the notification with a weird image.  If it causes a system reboot that is definitely not something I can do anything about since that is 100% a ROM problem.  There is nothing any app can do which should ever cause a system shutdown, and there is nothing an app can do to prevent such a huge bug in the system.
