### ISSUE TITLE
DSUB crash on orientation change in offline mode

### ISSUE THREAD

**Issue by SilentViking** [daneren2005/Subsonic#790]
To reproduce: tap go offline.
Initiate orientation change.
Watch dsub crash. Below is the exception output.

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{github.daneren2005.dsub/github.daneren2005.dsub.activity.SubsonicFragmentActivity}: java.lang.NullPointerException: Attempt to write to field 'int android.support.v4.app.Fragment.mNextAnim' on a null object reference
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4077)
    at android.app.ActivityThread.-wrap15(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
 Caused by: java.lang.NullPointerException: Attempt to write to field 'int android.support.v4.app.Fragment.mNextAnim' on a null object reference
    at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:770)
    at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1677)
    at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:589)
    at github.daneren2005.dsub.activity.SubsonicActivity.onRestoreInstanceState(SubsonicActivity.java:483)
    at github.daneren2005.dsub.activity.SubsonicFragmentActivity.onRestoreInstanceState(SubsonicFragmentActivity.java:485)
    at android.app.Activity.performRestoreInstanceState(Activity.java:959)
    at android.app.Instrumentation.callActivityOnRestoreInstanceState(Instrumentation.java:1163)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2389)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
    at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4077) 
    at android.app.ActivityThread.-wrap15(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.app.ActivityThread.main(ActivityThread.java:5417) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by daneren2005** [comment]
I wasn't having any luck reproducing.  Do you have to be on a specific screen?
