### ISSUE TITLE
Can't start music from bluetooth device

### ISSUE THREAD

**Issue by TheMagican** [daneren2005/Subsonic#937]
After connecting a bluetooth device (tested with car radio and bluetooth headset), I can not start the music playback: Pressing the play or next/previous song buttons have no effect. After opening DSub and starting the playback manually in the app, everything is fine and I can play / pause / skip using the controls of the bluetooth device. I can even pause the playback and restart it after a few minutes.

I also tried to open DSub automatically when I connect to a bluetooth device using [Tasker](https://play.google.com/store/apps/details?id=net.dinglisch.android.taskerm) but this didn't help either: Sometimes I can directly play music, sometimes I have to manually press the play button in DSub.

I also tried to configure the default music app using [Better open With](https://play.google.com/store/apps/details?id=com.aboutmycode.betteropenwith) but DSub doesn't get listed as a music app.

The problem ocurrs, when I haven't played music for a longer time (or after restarting the phone) and then connect to a bluetooth device. I googled a bit: May it be the case, that DSub doesn't start a [Media Session](https://developer.android.com/guide/topics/media-apps/mediabuttons) on device start (or something similar)?

Can someone give me a hint on how to debug / fix this problem? (Disclaimer: I'm a professional Java developer but haven't built Android apps yet.)

**My device:** bq Aquaris X2 Pro, Android 8.1.0 (Android One)

**Comment by KBerstene** [comment]
What are your notification settings?  Do you have persistent notifications enabled?

**Comment by TheMagican** [comment]
I'm not sure, which persistent notification you mean:
- When I get into `Android settings -> Apps -> DSub -> App-Notification` there is no option for a persistent notification. Neverthelss, nothing is disabled there.
- In `DSub settings -> Playback` I found an option for a persistent notification. This is indeed disabled. But I think, this isn't a solution as this notification will only be displayed *after* I've started the playback. My problem is, that I can't start the playback at all.

**Comment by HubbeKing** [comment]
Notifications from DSub seem to not act like media player notifications tend to do, and instead show up on my Garmin smartwatch as if they were simple text-only notifications.

**Comment by KBerstene** [comment]
Okay, I think I have figured this out.  Two things:
1) The service that handles the Media Session is getting killed by Android because it stops being a foreground app. When it gets killed, it disconnects from the system's media control buttons - bluetooth, lockscreen, etc.
2) I have a potential fix, but it uses @glennguy's excellent MediaStyle notifications, since they're more modern and integrate a bit better into the newer notification system.  I'm working out a few kinks, but I don't know when anything would be integrated into the main app.

**Comment by glennguy** [comment]
Does this issue also happen for GPM/Spotify etc.?

I have this issue too but for me the root cause is that since moving to sdk 26 it no longer auto plays when connecting to bluetooth. Solving that would fix both.

**Comment by KBerstene** [comment]
There may be a confluence of two issues here, namely the MediaSession being unregistered and also DSub not being properly recognized as a music app by some functions.

**Comment by KBerstene** [comment]
Okay, I think I have a solution.  The code is in a branch of mine here: https://github.com/KBerstene/Subsonic/tree/bugfix/staticMediaSession

I would love to have this tested before opening a pull request.  @TheMagican @HubbeKing, would you mind testing it out to see if you see improved behavior?

@glennguy, I do not believe this fixes the auto-play when connecting to bluetooth issue, but I would love to find out that it does.

**Comment by HubbeKing** [comment]
@KBerstene 
Getting a crash with the following stacktrace when trying to input my server settings into your fixed version:
`2019-06-15 17:00:23.062 12495-12495/github.daneren2005.dsub E/AndroidRuntime: FATAL EXCEPTION: main
    Process: github.daneren2005.dsub, PID: 12495
    android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{c14e499 u0 github.daneren2005.dsub/.service.DownloadService}
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1752)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:198)
        at android.app.ActivityThread.main(ActivityThread.java:6729)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)`

**Comment by KBerstene** [comment]
@HubbeKing that's interesting, I can't seem to reproduce that or figure out exactly why that's happening.  Nothing that I did should have affected server settings.  If there's a longer stack trace, I would love to see it.
