### ISSUE TITLE
Potential race condition failure in Android Auto album art bugfix

### ISSUE THREAD

**Issue by Koenvh1** [daneren2005/Subsonic#950]
The following commit contains a race condition: https://github.com/daneren2005/Subsonic/commit/66013243709b759a57d1e0403f1e7d6d2d8ff438
`imageLoader.loadImage` returns a task, where it is uncertain how long it takes to execute, but `imageLoader.getCachedImage` expects an image to be already present, meaning that if it takes a bit longer than expected, it will fail, and an error will be shown:
![afbeelding](https://user-images.githubusercontent.com/5168825/56284621-4c128380-6115-11e9-9ea4-a03311379660.png)

Relevant stacktrace:
```
W/BackgroundTask: Got exception: java.lang.NullPointerException: key == null || value == null
    java.lang.NullPointerException: key == null || value == null
        at android.support.v4.util.LruCache.put(LruCache.java:134)
        at github.daneren2005.dsub.util.ImageLoader.getCachedImage(ImageLoader.java:210)
        at github.daneren2005.dsub.util.compat.RemoteControlClientLP.updateMetadata(RemoteControlClientLP.java:185)
        at github.daneren2005.dsub.service.DownloadService.setCurrentPlaying(DownloadService.java:929)
        at github.daneren2005.dsub.service.DownloadService.setCurrentPlaying(DownloadService.java:904)
        at github.daneren2005.dsub.service.DownloadService.play(DownloadService.java:1146)
        at github.daneren2005.dsub.service.DownloadService.download(DownloadService.java:502)
        at github.daneren2005.dsub.fragments.SubsonicFragment.playNowInTask(SubsonicFragment.java:1780)
        at github.daneren2005.dsub.fragments.SubsonicFragment$21.doInBackground(SubsonicFragment.java:1760)
        at github.daneren2005.dsub.fragments.SubsonicFragment$21.doInBackground(SubsonicFragment.java:1757)
        at github.daneren2005.dsub.util.BackgroundTask$Task.execute(BackgroundTask.java:208)
        at github.daneren2005.dsub.util.BackgroundTask$Task.access$300(BackgroundTask.java:194)
        at github.daneren2005.dsub.util.BackgroundTask$TaskRunnable.run(BackgroundTask.java:319)
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by KBerstene** [comment]
Since that's my borked bugfix, I will work on a fix for it very soon.  Thanks for bringing this up!
