### ISSUE TITLE
StackOverflowError

### ISSUE THREAD

**Issue by openpaul** [daneren2005/Subsonic#962]
I am using app version 5.4.4 on android 9 in combination with a Funkwhale installation (0.19.1).

My library only contains a single song at the moment but the dsub app keeps crashing when I click on the artist (click path: Library > "Artist Name" > CRASH).

I fetched the "dsub-stacktrace.txt" file showing that it is a StackOverflowError:

[dsub-stacktrace.txt](https://github.com/daneren2005/Subsonic/files/3482623/dsub-stacktrace.txt)

As I am not using a supported server I don't expect much support but wanted to file the bug report regardless. 

These are the dsub related lines from logcat:

```
08-08 16:52:44.422  8519  8562 E AndroidRuntime:        at github.daneren2005.dsub.util.FileUtil.getSongFile(FileUtil.java:116)
08-08 16:52:44.422  8519  8562 E AndroidRuntime:        at github.daneren2005.dsub.util.FileUtil.getAlbumDirectory(FileUtil.java:358)
08-08 16:52:44.422  8519  8562 E AndroidRuntime:        at github.daneren2005.dsub.util.FileUtil.getSongFile(FileUtil.java:116)
08-08 16:52:44.422  8519  8562 E AndroidRuntime:        at github.daneren2005.dsub.util.FileUtil.getAlbumDirectory(FileUtil.java:358)
08-08 16:52:44.422  8519  8562 E AndroidRuntime:        at github.daneren2005.dsub.view.AlbumView.updateBackground(AlbumView.java:99)
08-08 16:52:44.422  8519  8562 E AndroidRuntime:        at github.daneren2005.dsub.view.UpdateView2$1.run(UpdateView2.java:40)
08-08 16:52:44.422  8519  8562 E AndroidRuntime:        at github.daneren2005.dsub.view.UpdateView$2.run(UpdateView.java:138)
08-08 16:52:44.439  8519  8562 I SubsonicActivity: Stack trace written to /storage/emulated/0/dsub-stacktrace.txt
08-08 16:52:44.456  2850  4218 W ActivityManager:   Force finishing activity github.daneren2005.dsub/.activity.SubsonicFragmentActivity
08-08 16:52:44.472  2850  2880 I ActivityManager: Showing crash dialog for package github.daneren2005.dsub u0
08-08 16:52:44.496  8519  8528 I chatty  : uid=10142(github.daneren2005.dsub) FinalizerDaemon identical 8 lines
08-08 16:52:44.860   273  1562 W SurfaceFlinger: Attempting to destroy on removed layer: AppWindowToken{488cf2a token=Token{df6f015 ActivityRecord{274a5cc u0 github.daneren2005.dsub/.activity.SubsonicFragmentActivity t655}}}#0
````

The app works fine with the test server.

**Comment by openpaul** [comment]
The bug was gone after I added more music. 
I think it had something to do with the fact that I uploaded this single song using funkwhales web UI. 

The rest I added using the command line and now it works fine.

I am closing this issue as it is resolved for me.
